tasks:
  generate:
    action: !generateLibSources
      libsDir: ${module.rootDir}
      resourcesDir: ${taskOutputDir}
generated:
  resources:
    - directory: ${tasks.generate.action.resourcesDir}
    
#    markOutputsAs:
#      - path: ${action.resourcesDir}
#        kind: jvm-resources

