[versions]
accompanist = "0.37.0"
agp = "8.11.2"
androidCompileSdk = "36"
androidDesugarJdkLibs = "2.1.4"
androidGradlePlugin = "9.0.0"
androidMinSdk = "24"
androidTargetSdk = "36"
androidTools = "32.0.0"
androidxActivity = "1.12.2"
androidxAppCompat = "1.7.0"
androidxAppcompat = "1.7.1"
androidxBrowser = "1.8.0"
androidxComposeBom = "2025.09.01"
androidxComposeFoundation = "1.8.0-alpha07"
androidxComposeMaterial3Adaptive = "1.1.0-rc01"
androidxComposeMaterial3AdaptiveNavigation3 = "1.3.0-alpha04"
androidxComposeRuntimeTracing = "1.7.6"
androidxCore = "1.17.0"
androidxCoreSplashscreen = "1.0.1"
androidxCoreSplasscreen = "1.2.0"
androidxDataStore = "1.2.0"
androidxEspresso = "3.7.0"
androidxHiltLifecycleViewModelCompose = "1.3.0-alpha02"
#androidxLifecycle = "2.10.0"
#androidxLifecycle = "2.9.4"
androidxLifecycle = "2.9.6"
androidxLifecycleViewModelNavigation3 = "2.10.0"
androidxLintGradle = "1.0.0-alpha03"
androidxMacroBenchmark = "1.5.0-alpha01"
androidxMetrics = "1.0.0-beta01"
androidxNavigation = "2.8.5"
androidxNavigation3 = "1.0.0"
androidxProfileinstaller = "1.4.1"
androidxSavedStateCompose = "1.3.1"
androidxTestCore = "1.7.0-rc01"
androidxTestExt = "1.3.0"
androidxTestRules = "1.7.0-rc01"
androidxTestRunner = "1.7.0-rc01"
androidxTracing = "1.3.0-alpha02"
androidxUiAutomator = "2.3.0"
androidxWindowManager = "1.3.0"
androidxWork = "2.10.0"
brComDevsrsouzaComposeIcons = "1.1.1"
coil = "3.3.0"
composeHotReload = "1.0.0-rc03"
composeMultiplatform = "1.10.0"
config = "1.4.5"
datastore = "1.2.0-rc01"
dependencyGuard = "0.5.0"
exposed = "1.0.0"
firebaseBom = "33.7.0"
firebaseCrashlyticsPlugin = "3.0.6"
firebasePerfPlugin = "2.0.2"
gmsPlugin = "4.4.4"
googleOss = "17.1.0"
googleOssPlugin = "0.10.9"
h2 = "2.4.240"
hikaricp = "7.0.2"
hilt = "2.59"
hiltExt = "1.2.0"
jacoco = "0.8.12"
junit4 = "4.13.2"
koin = "4.1.1"
kotlin = "2.3.20"
kotlinSerialization = "1.10.0"
kotlinxCcoroutines = "1.10.2"
kotlinxCoroutines = "1.10.1"
kotlinxDatetime = "0.6.1"
kotlinxRpc = "0.10.2"
kotlinxSerializationJson = "1.8.0"
ksp = "2.3.4"
ktlint = "1.4.0"
ktor = "3.4.1"
lifecycleViewmodelNav3 = "2.10.0-beta01"
logback = "1.5.24"
material = "1.5.2"
material3 = "1.10.0-alpha05"
material3AdaptiveNav3 = "1.3.0-alpha02"
multiplatformSettings = "1.3.0"
nav3Core = "1.0.0-beta01"
okhttp = "4.12.0"
postgres = "42.7.8"
protobuf = "4.29.2"
protobufPlugin = "0.9.6"
retrofit = "2.11.0"
retrofitKotlinxSerializationJson = "1.0.0"
robolectric = "4.16"
roborazzi = "1.56.0"
room = "2.8.3"
slf4j = "2.0.17"
sonner = "0.3.9"
spotless = "8.3.0"
truth = "1.4.4"
turbine = "1.2.0"
uiTestJunit4 = "1.9.0-rc01"
voyagerVersion = "1.1.0-beta03"

[bundles]
androidx-compose-ui-test = ["androidx-compose-ui-test", "androidx-compose-ui-testManifest"]

[libraries]
#androidx.activity = { module = "androidx.activity:activity", version = "1.8.1" }
androidx.activity.compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx.appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx.core.ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx.core.splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxCoreSplasscreen" }
androidx.compose.uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
androidx.datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx.datastore.core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
androidx.datastore.preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx.espresso.core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx.lifecycle.liveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx.lifecycle.runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidxLifecycle" }
androidx.lifecycle.runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx.lifecycle.viewmodel.navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx.lifecycle.viewmodel.compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx.material3.adaptive.navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }
androidx.navigation3.runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx.navigation3.ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx.testExt.junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }

coil.compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil.network.okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
config = { module = "com.typesafe:config", version.ref = "config" }

compose.animation ={ module =  "org.jetbrains.compose.animation:animation", version.ref = "composeMultiplatform" }
compose.animationGraphics = { module = "org.jetbrains.compose.animation:animation-graphics", version.ref = "composeMultiplatform" }
compose.components.resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose.desktop.common = { module = "org.jetbrains.compose.desktop:desktop", version.ref = "composeMultiplatform" }
compose.desktop.components.animatedImage ={ module =  "org.jetbrains.compose.components:components-animatedimage", version.ref = "composeMultiplatform" }
compose.desktop.components.splitPane = { module = "org.jetbrains.compose.components:components-splitpane", version.ref = "composeMultiplatform" }
compose.desktop.currentOs = { module = "org.jetbrains.compose.desktop:desktop-jvm-windows-x64", version.ref = "composeMultiplatform" }
compose.desktop.linux_arm64 ={ module =  "org.jetbrains.compose.desktop:desktop-jvm-linux-arm64", version.ref = "composeMultiplatform" }
compose.desktop.linux_x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-linux-x64", version.ref = "composeMultiplatform" }
compose.desktop.macos_arm64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-arm64", version.ref = "composeMultiplatform" }
compose.desktop.macos_x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-x64", version.ref = "composeMultiplatform" }
compose.desktop.uiTestJUnit4 = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "composeMultiplatform" }
compose.desktop.windows_x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-windows-x64", version.ref = "composeMultiplatform" }
compose.foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose.hotReload.runtimeApi = { module =  "org.jetbrains.compose.hot-reload:hot-reload-runtime-api", version.ref = "composeHotReload" }
compose.hot.reload.runtime = { module = "org.jetbrains.compose.hot-reload:hot-reload-runtime-jvm", version.ref = "composeHotReload" }
compose.html.core = "org.jetbrains.compose.html:html-core:1.8.2"
compose.html.svg = "org.jetbrains.compose.html:html-svg:1.8.2"
compose.html.testUtils = "org.jetbrains.compose.html:html-test-utils:1.8.2"
compose.material = { module = "org.jetbrains.compose.material:material", version.ref = "material" }
compose.material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose.material3.windows = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "material3" }
compose.materialIconsCore = "org.jetbrains.compose.material:material-icons-core:1.7.3"
compose.materialIconsExtended = "org.jetbrains.compose.material:material-icons-extended:1.7.3"
compose.preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose.runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose.runtimeSaveable = "org.jetbrains.compose.runtime:runtime-saveable:1.8.2"
compose.ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose.uiTest = "org.jetbrains.compose.ui:ui-test:1.8.0"
compose.uiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
compose.uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }

exposed.core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed.dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed.datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed.jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
feather = { module = "br.com.devsrsouza.compose.icons:feather", version.ref = "brComDevsrsouzaComposeIcons" }
font.awesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "brComDevsrsouzaComposeIcons" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hikariCP = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
#junit = { module = "junit:junit", version.ref = "junit" }
koin.compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin.compose.viewModel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin.core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin.ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin.logger.slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
kotlin.reflect = "org.jetbrains.kotlin:kotlin-reflect:2.2.0"
kotlin.test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin.test.junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinx.coroutines.android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCcoroutines" }
kotlinx.coroutines.core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCcoroutines" }
kotlinx.coroutines.swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCcoroutines" }
kotlinx.datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"
kotlinx.rpc.core = { module = "org.jetbrains.kotlinx:kotlinx-rpc-core", version.ref = "kotlinxRpc" }
kotlinx.rpc.krpc.client = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-client", version.ref = "kotlinxRpc" }
kotlinx.rpc.krpc.server = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-server", version.ref = "kotlinxRpc" }
kotlinx.rpc.krpc.serialization.json = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-serialization-json", version.ref = "kotlinxRpc" }
kotlinx.rpc.krpc.ktor.client = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-ktor-client", version.ref = "kotlinxRpc" }
kotlinx.rpc.krpc.ktor.server = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-ktor-server", version.ref = "kotlinxRpc" }
kotlinx.serialization.cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinSerialization" }
kotlinx.serialization.core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinSerialization" }
kotlinx.serialization.hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "kotlinSerialization" }
kotlinx.serialization.json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlinx.serialization.json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlinSerialization" }
kotlinx.serialization.properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "kotlinSerialization" }
kotlinx.serialization.protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinSerialization" }

ktor.auth = "io.ktor:ktor-auth"
ktor.auth.jwt = "io.ktor:ktor-auth-jwt"
ktor.auth.ldap = "io.ktor:ktor-auth-ldap"
ktor.bom = "io.ktor:ktor-bom:3.1.1"
ktor.callId = "io.ktor:ktor-call-id"
ktor.client = "io.ktor:ktor-client"
ktor.client.apache = "io.ktor:ktor-client-apache"
ktor.client.apache5 = "io.ktor:ktor-client-apache5"
ktor.client.auth = "io.ktor:ktor-client-auth"
ktor.client.authBasic = "io.ktor:ktor-client-auth-basic"
ktor.client.callId = "io.ktor:ktor-client-call-id"
ktor.client.cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor.client.contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor.client.core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor.client.encoding = "io.ktor:ktor-client-encoding"
ktor.client.features = "io.ktor:ktor-client-features"
ktor.client.gson = "io.ktor:ktor-client-gson"
ktor.client.jackson = "io.ktor:ktor-client-jackson"
ktor.client.java = "io.ktor:ktor-client-java"
ktor.client.jetty = "io.ktor:ktor-client-jetty"
ktor.client.jetty.jakarta = "io.ktor:ktor-client-jetty-jakarta"
ktor.client.json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor.client.logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor.client.mock = "io.ktor:ktor-client-mock"
ktor.client.okhttp = "io.ktor:ktor-client-okhttp"
ktor.client.plugins = "io.ktor:ktor-client-plugins"
ktor.client.resources = "io.ktor:ktor-client-resources"
ktor.client.serialization = "io.ktor:ktor-client-serialization"
ktor.client.websocket = "io.ktor:ktor-client-websocket"
ktor.client.websockets = "io.ktor:ktor-client-websockets"
ktor.client.winhttp = "io.ktor:ktor-client-winhttp"
ktor.events = "io.ktor:ktor-events"
ktor.features = "io.ktor:ktor-features"
ktor.freemarker = "io.ktor:ktor-freemarker"
ktor.gson = "io.ktor:ktor-gson"
ktor.html.builder = "io.ktor:ktor-html-builder"
ktor.http = "io.ktor:ktor-http"
ktor.http.cio = "io.ktor:ktor-http-cio"
ktor.io = "io.ktor:ktor-io"
ktor.jackson = "io.ktor:ktor-jackson"
ktor.locations = "io.ktor:ktor-locations"
ktor.metrics = "io.ktor:ktor-metrics"
ktor.metrics.micrometer = "io.ktor:ktor-metrics-micrometer"
ktor.mustache = "io.ktor:ktor-mustache"
ktor.network = "io.ktor:ktor-network"
ktor.network.tls = "io.ktor:ktor-network-tls"
ktor.network.tls.certificates = "io.ktor:ktor-network-tls-certificates"
ktor.pebble = "io.ktor:ktor-pebble"
ktor.resources = "io.ktor:ktor-resources"
ktor.serialization = "io.ktor:ktor-serialization"
ktor.serialization.gson = "io.ktor:ktor-serialization-gson"
ktor.serialization.jackson = "io.ktor:ktor-serialization-jackson"
ktor.serialization.kotlinx = "io.ktor:ktor-serialization-kotlinx"
ktor.serialization.kotlinx.cbor = "io.ktor:ktor-serialization-kotlinx-cbor"
ktor.serialization.kotlinx.json = "io.ktor:ktor-serialization-kotlinx-json"
ktor.serialization.kotlinx.json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor.serialization.kotlinx.protobuf = "io.ktor:ktor-serialization-kotlinx-protobuf"
ktor.serialization.kotlinx.xml = "io.ktor:ktor-serialization-kotlinx-xml"
ktor.server.auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor.server.auth.jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor.server.auth.ldap = "io.ktor:ktor-server-auth-ldap"
ktor.server.autoHeadResponse = "io.ktor:ktor-server-auto-head-response"
ktor.server.bodyLimit = "io.ktor:ktor-server-body-limit"
ktor.server.cachingHeaders = "io.ktor:ktor-server-caching-headers"
ktor.server.callId = "io.ktor:ktor-server-call-id"
ktor.server.callLogging = "io.ktor:ktor-server-call-logging"
ktor.server.cio = "io.ktor:ktor-server-cio"
ktor.server.compression = "io.ktor:ktor-server-compression"
ktor.server.conditionalHeaders = "io.ktor:ktor-server-conditional-headers"
ktor.server.config.yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor.server.content.negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor.server.core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor.server.core.jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor.server.cors = "io.ktor:ktor-server-cors"
ktor.server.csrf = "io.ktor:ktor-server-csrf"
ktor.server.dataConversion = "io.ktor:ktor-server-data-conversion"
ktor.server.defaultHeaders = "io.ktor:ktor-server-default-headers"
ktor.server.doubleReceive = "io.ktor:ktor-server-double-receive"
ktor.server.forwardedHeader = "io.ktor:ktor-server-forwarded-header"
ktor.server.freemarker = "io.ktor:ktor-server-freemarker"
ktor.server.hsts = "io.ktor:ktor-server-hsts"
ktor.server.htmlBuilder = "io.ktor:ktor-server-html-builder"
ktor.server.httpRedirect = "io.ktor:ktor-server-http-redirect"
ktor.server.i18n = "io.ktor:ktor-server-i18n"
ktor.server.jetty = "io.ktor:ktor-server-jetty"
ktor.server.jetty.jakarta = "io.ktor:ktor-server-jetty-jakarta"
ktor.server.jte = "io.ktor:ktor-server-jte"
ktor.server.locations = "io.ktor:ktor-server-locations"
ktor.server.methodOverride = "io.ktor:ktor-server-method-override"
ktor.server.metrics = "io.ktor:ktor-server-metrics"
ktor.server.metrics.micrometer = "io.ktor:ktor-server-metrics-micrometer"
ktor.server.mustache = "io.ktor:ktor-server-mustache"
ktor.server.netty.jvm = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor.server.netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor.server.openapi = "io.ktor:ktor-server-openapi"
ktor.server.partialContent = "io.ktor:ktor-server-partial-content"
ktor.server.pebble = "io.ktor:ktor-server-pebble"
ktor.server.plugins = "io.ktor:ktor-server-plugins"
ktor.server.rateLimit = "io.ktor:ktor-server-rate-limit"
ktor.server.requestValidation = "io.ktor:ktor-server-request-validation"
ktor.server.resources = "io.ktor:ktor-server-resources"
ktor.server.servlet = "io.ktor:ktor-server-servlet"
ktor.server.servlet.jakarta = "io.ktor:ktor-server-servlet-jakarta"
ktor.server.sessions = "io.ktor:ktor-server-sessions"
ktor.server.sse = "io.ktor:ktor-server-sse"
ktor.server.statusPages = "io.ktor:ktor-server-status-pages"
ktor.server.swagger = "io.ktor:ktor-server-swagger"
ktor.server.test.host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor.server.test.host.jvm = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
ktor.server.thymeleaf = "io.ktor:ktor-server-thymeleaf"
ktor.server.tomcat = "io.ktor:ktor-server-tomcat"
ktor.server.tomcat.jakarta = "io.ktor:ktor-server-tomcat-jakarta"
ktor.server.velocity = "io.ktor:ktor-server-velocity"
ktor.server.webjars = "io.ktor:ktor-server-webjars"
ktor.server.websockets = "io.ktor:ktor-server-websockets"
ktor.sse = "io.ktor:ktor-sse"
ktor.thymeleaf = "io.ktor:ktor-thymeleaf"
ktor.utils = "io.ktor:ktor-utils"
ktor.velocity = "io.ktor:ktor-velocity"
ktor.webjars = "io.ktor:ktor-webjars"
ktor.websocket.serialization = "io.ktor:ktor-websocket-serialization"
ktor.websockets = "io.ktor:ktor-websockets"

multiplatform.settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform.settings.serialization = { module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "multiplatformSettings" }
multiplatform.settings.datastore ={ module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "multiplatformSettings" }
multiplatform.settings.coroutines={ module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }

logback.classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }
slf4j.api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j.nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
voyager.navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyagerVersion" }
voyager.tab.navigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyagerVersion" }
voyager.transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyagerVersion" }




[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlin.plugin.serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
kotlin.jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinx.rpc = { id = "org.jetbrains.kotlinx.rpc.plugin", version.ref = "kotlinxRpc" }