[versions]
accompanist = "0.37.0"
agp = "8.11.2"
androidCompileSdk = "36"
androidDesugarJdkLibs = "2.1.4"
androidGradlePlugin = "9.0.0"
androidMinSdk = "27"
androidTargetSdk = "36"
androidTools = "32.0.0"
androidxActivity = "1.13.0"
androidxAppcompat = "1.7.1"
androidxBrowser = "1.8.0"
androidxComposeBom = "2025.09.01"
androidxComposeFoundation = "1.8.0-alpha07"
androidxComposeMaterial3Adaptive = "1.1.0-rc01"
androidxComposeMaterial3AdaptiveNavigation3 = "1.3.0-alpha04"
androidxComposeRuntimeTracing = "1.7.6"
androidxCore = "1.18.0"
androidxCoreSplashscreen = "1.0.1"
androidxCoreSplasscreen = "1.2.0"
androidxDataStore = "1.2.0"
androidxEspresso = "3.7.0"
androidxHiltLifecycleViewModelCompose = "1.3.0-alpha02"
androidxLifecycle = "2.11.0-beta01"
androidxLifecycleViewModelNavigation3 = "2.10.0"
androidxLintGradle = "1.0.0-alpha03"
androidxMacroBenchmark = "1.5.0-alpha01"
androidxMetrics = "1.0.0-beta01"
androidxNavigation = "2.8.5"
androidxNavigation3 = "1.0.0"
androidxPaging = "3.5.0-beta01"
androidxProfileinstaller = "1.4.1"
androidxSavedStateCompose = "1.3.1"
androidxTestCore = "1.7.0-rc01"
androidxTestExt = "1.3.0"
androidxTestRules = "1.7.0-rc01"
androidxTestRunner = "1.7.0-rc01"
androidxTracing = "1.3.0-alpha02"
androidxUiAutomator = "2.3.0"
androidxWindowManager = "1.3.0"
androidxWork = "2.10.0"
brComDevsrsouzaComposeIcons = "1.1.1"
coil = "3.3.0"
composeHotReload = "1.1.1"
composeMultiplatform = "1.11.1"
composeRemote = "1.0.0-alpha03"
config = "1.4.8"
datastore = "1.2.0-rc01"
dependencyGuard = "0.5.0"
exposed = "1.0.0"
firebaseBom = "33.7.0"
firebaseCrashlyticsPlugin = "3.0.6"
firebasePerfPlugin = "2.0.2"
gmsPlugin = "4.4.4"
googleOss = "17.1.0"
googleOssPlugin = "0.10.9"
h2 = "2.4.240"
hikaricp = "7.0.2"
hilt = "2.59"
hiltExt = "1.2.0"
jacoco = "0.8.12"
junit4 = "4.13.2"
koin = "4.1.1"
kotlin = "2.4.0"
kotlinSerialization = "1.11.0"
kotlinxCcoroutines = "1.11.0"
kotlinxCoroutines = "1.11.0"
kotlinxDatetime = "0.7.1"
kotlinxRpc = "0.10.2"
ksp = "2.3.6"
ktlint = "1.4.0"
ktor = "3.5.0"
lifecycleViewmodelNav3 = "2.10.0-beta01"
logback = "1.5.32"
material = "1.5.2"
material3 = "1.11.0-alpha07"
material3AdaptiveNav3 = "1.3.0-alpha02"
mmkv = "2.4.0"
multiplatformSettings = "1.3.0"
nav3Core = "1.0.0-beta01"
okhttp = "4.12.0"
postgres = "42.7.11"
protobuf = "4.29.2"
protobufPlugin = "0.9.6"
retrofit = "2.11.0"
retrofitKotlinxSerializationJson = "1.0.0"
robolectric = "4.16"
roborazzi = "1.56.0"
room = "2.8.4"
room3 = "3.0.0-alpha06"
slf4j = "2.0.18"
sonner = "0.3.9"
spotless = "8.3.0"
truth = "1.4.4"
turbine = "1.2.0"
uiTestJunit4 = "1.9.0-rc01"
voyager = "1.1.0-beta03"

[bundles]
androidx-compose-ui-test = ["androidx-compose-ui-test", "androidx-compose-ui-testManifest"]

[libraries]

js.joda.core = "org.webjars.npm:js-joda__core:3.2.0"
#androidx.activity = { module = "androidx.activity:activity", version = "1.8.1" }
androidx.activity.compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx.appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx.core.ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx.core.splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxCoreSplasscreen" }
androidx.compose.uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
androidx.compose.runtime = { module = "androidx.compose.runtime:runtime", version.ref = "composeMultiplatform" }
androidx.compose.livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "composeMultiplatform" }
androidx.compose.remote.core = { module = "androidx.compose.remote:remote-core", version.ref = "composeRemote" }
# Use to create Remote Compose documents
androidx.compose.remote.creation = { module = "androidx.compose.remote:remote-creation", version.ref = "composeRemote" }
androidx.compose.remote.creation.core = { module = "androidx.compose.remote:remote-creation-core", version.ref = "composeRemote" }
androidx.compose.remote.creation.compose = { module = "androidx.compose.remote:remote-creation-compose", version.ref = "composeRemote" }
# Use to render a Remote Compose document
androidx.compose.remote.player.core = { module = "androidx.compose.remote:remote-player-core", version.ref = "composeRemote" }
androidx.compose.remote.player.view = { module = "androidx.compose.remote:remote-player-view", version.ref = "composeRemote" }
androidx.compose.remote.tooling.preview = { module = "androidx.compose.remote:remote-tooling-preview", version.ref = "composeRemote" }
androidx.compose.remote.remote.creation.android = { module = "androidx.compose.remote:remote-creation-android", version.ref = "composeRemote" }
androidx.datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx.datastore.core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
androidx.datastore.preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx.espresso.core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx.lifecycle.liveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx.lifecycle.runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidxLifecycle" }
androidx.lifecycle.runtime.ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx.lifecycle.viewmodel.ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx.lifecycle.viewmodel.compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx.lifecycle.runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx.lifecycle.viewmodel.compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx.lifecycle.viewmodel.navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx.material3.adaptive.navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }
androidx.navigation3.runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx.navigation3.ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx.paging.common = { module = "androidx.paging:paging-common", version.ref = "androidxPaging" }
androidx.paging.compose = { module = "androidx.paging:paging-compose", version.ref = "androidxPaging" }
androidx.testExt.junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx.room.compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx.room.ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx.room.paging = { module = "androidx.room:room-paging", version.ref = "room" }

androidx.room3.common = { module = "androidx.room3:room3-common", version.ref = "room3" }
androidx.room3.runtime = { module = "androidx.room3:room3-runtime", version.ref = "room3" }
androidx.room3.paging = { module = "androidx.room3:room3-paging", version.ref = "room3" }

coil.compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil.network.okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
config = { module = "com.typesafe:config", version.ref = "config" }

compose.animation = { module = "org.jetbrains.compose.animation:animation", version.ref = "composeMultiplatform" }
compose.animationGraphics = { module = "org.jetbrains.compose.animation:animation-graphics", version.ref = "composeMultiplatform" }
compose.components.resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose.desktop.common = { module = "org.jetbrains.compose.desktop:desktop", version.ref = "composeMultiplatform" }
compose.desktop.components.animatedImage = { module = "org.jetbrains.compose.components:components-animatedimage", version.ref = "composeMultiplatform" }
compose.desktop.components.splitPane = { module = "org.jetbrains.compose.components:components-splitpane", version.ref = "composeMultiplatform" }
compose.desktop.currentOs = { module = "org.jetbrains.compose.desktop:desktop-jvm-windows-x64", version.ref = "composeMultiplatform" }
compose.desktop.linux_arm64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-linux-arm64", version.ref = "composeMultiplatform" }
compose.desktop.linux_x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-linux-x64", version.ref = "composeMultiplatform" }
compose.desktop.macos_arm64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-arm64", version.ref = "composeMultiplatform" }
compose.desktop.macos_x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-x64", version.ref = "composeMultiplatform" }
compose.desktop.uiTestJUnit4 = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "composeMultiplatform" }
compose.desktop.windows_x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-windows-x64", version.ref = "composeMultiplatform" }
compose.foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose.hotReload.runtimeApi = { module = "org.jetbrains.compose.hot-reload:hot-reload-runtime-api", version.ref = "composeHotReload" }
compose.hot.reload.runtime = { module = "org.jetbrains.compose.hot-reload:hot-reload-runtime-jvm", version.ref = "composeHotReload" }
compose.html.core = "org.jetbrains.compose.html:html-core:1.8.2"
compose.html.svg = "org.jetbrains.compose.html:html-svg:1.8.2"
compose.html.testUtils = "org.jetbrains.compose.html:html-test-utils:1.8.2"
compose.material = { module = "org.jetbrains.compose.material:material", version.ref = "material" }
compose.material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose.material3.windows = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "material3" }
compose.materialIconsCore = "org.jetbrains.compose.material:material-icons-core:1.7.3"
compose.materialIconsExtended = "org.jetbrains.compose.material:material-icons-extended:1.7.3"
compose.preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose.runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose.runtimeSaveable = "org.jetbrains.compose.runtime:runtime-saveable:1.8.2"
compose.ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose.uiTest = "org.jetbrains.compose.ui:ui-test:1.8.0"
compose.uiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
compose.uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }

exposed.core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed.dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed.datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed.jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
feather = { module = "br.com.devsrsouza.compose.icons:feather", version.ref = "brComDevsrsouzaComposeIcons" }
font.awesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "brComDevsrsouzaComposeIcons" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hikariCP = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
#junit = { module = "junit:junit", version.ref = "junit" }
koin.annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin" }
koin.compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin.compose.viewModel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin.core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin.ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin.logger.slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
kotlin.reflect = "org.jetbrains.kotlin:kotlin-reflect:2.2.0"
kotlin.test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin.test.junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinx.coroutines.android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCcoroutines" }
kotlinx.coroutines.core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCcoroutines" }
kotlinx.coroutines.swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCcoroutines" }
kotlinx.datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx.rpc.core = { module = "org.jetbrains.kotlinx:kotlinx-rpc-core", version.ref = "kotlinxRpc" }
kotlinx.rpc.krpc.client = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-client", version.ref = "kotlinxRpc" }
kotlinx.rpc.krpc.server = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-server", version.ref = "kotlinxRpc" }
kotlinx.rpc.krpc.serialization.json = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-serialization-json", version.ref = "kotlinxRpc" }
kotlinx.rpc.krpc.ktor.client = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-ktor-client", version.ref = "kotlinxRpc" }
kotlinx.rpc.krpc.ktor.server = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-ktor-server", version.ref = "kotlinxRpc" }
kotlinx.serialization.cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinSerialization" }
kotlinx.serialization.core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinSerialization" }
kotlinx.serialization.hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "kotlinSerialization" }
kotlinx.serialization.json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlinx.serialization.json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlinSerialization" }
kotlinx.serialization.properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "kotlinSerialization" }
kotlinx.serialization.protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinSerialization" }

ktor.auth = { module = "io.ktor:ktor-auth", version.ref = "ktor" }
ktor.auth.jwt = { module = "io.ktor:ktor-auth-jwt", version.ref = "ktor" }
ktor.auth.ldap = { module = "io.ktor:ktor-auth-ldap", version.ref = "ktor" }
ktor.bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor.callId = { module = "io.ktor:ktor-call-id", version.ref = "ktor" }
ktor.client = { module = "io.ktor:ktor-client", version.ref = "ktor" }
ktor.client.apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor.client.apache5 = { module = "io.ktor:ktor-client-apache5", version.ref = "ktor" }
ktor.client.auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor.client.authBasic = { module = "io.ktor:ktor-client-auth-basic", version.ref = "ktor" }
ktor.client.callId = { module = "io.ktor:ktor-client-call-id", version.ref = "ktor" }
ktor.client.cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor.client.contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor.client.core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor.client.encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor.client.features = { module = "io.ktor:ktor-client-features", version.ref = "ktor" }
ktor.client.gson = { module = "io.ktor:ktor-client-gson", version.ref = "ktor" }
ktor.client.jackson = { module = "io.ktor:ktor-client-jackson", version.ref = "ktor" }
ktor.client.java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor.client.jetty = { module = "io.ktor:ktor-client-jetty", version.ref = "ktor" }
ktor.client.jetty.jakarta = { module = "io.ktor:ktor-client-jetty-jakarta", version.ref = "ktor" }
ktor.client.json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor.client.logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor.client.mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor.client.okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor.client.plugins = { module = "io.ktor:ktor-client-plugins", version.ref = "ktor" }
ktor.client.resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor.client.serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor.client.websocket = { module = "io.ktor:ktor-client-websocket", version.ref = "ktor" }
ktor.client.websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor.client.winhttp = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }
ktor.events = { module = "io.ktor:ktor-events", version.ref = "ktor" }
ktor.features = { module = "io.ktor:ktor-features", version.ref = "ktor" }
ktor.freemarker = { module = "io.ktor:ktor-freemarker", version.ref = "ktor" }
ktor.gson = { module = "io.ktor:ktor-gson", version.ref = "ktor" }
ktor.html.builder = { module = "io.ktor:ktor-html-builder", version.ref = "ktor" }
ktor.http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor.http.cio = { module = "io.ktor:ktor-http-cio", version.ref = "ktor" }
ktor.io = { module = "io.ktor:ktor-io", version.ref = "ktor" }
ktor.jackson = { module = "io.ktor:ktor-jackson", version.ref = "ktor" }
ktor.locations = { module = "io.ktor:ktor-locations", version.ref = "ktor" }
ktor.metrics = { module = "io.ktor:ktor-metrics", version.ref = "ktor" }
ktor.metrics.micrometer = { module = "io.ktor:ktor-metrics-micrometer", version.ref = "ktor" }
ktor.mustache = { module = "io.ktor:ktor-mustache", version.ref = "ktor" }
ktor.network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
ktor.network.tls = { module = "io.ktor:ktor-network-tls", version.ref = "ktor" }
ktor.network.tls.certificates = { module = "io.ktor:ktor-network-tls-certificates", version.ref = "ktor" }
ktor.pebble = { module = "io.ktor:ktor-pebble", version.ref = "ktor" }
ktor.resources = { module = "io.ktor:ktor-resources", version.ref = "ktor" }
ktor.serialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor" }
ktor.serialization.gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }
ktor.serialization.jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktor.serialization.kotlinx = { module = "io.ktor:ktor-serialization-kotlinx", version.ref = "ktor" }
ktor.serialization.kotlinx.cbor = { module = "io.ktor:ktor-serialization-kotlinx-cbor", version.ref = "ktor" }
ktor.serialization.kotlinx.json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor.serialization.kotlinx.protobuf = { module = "io.ktor:ktor-serialization-kotlinx-protobuf", version.ref = "ktor" }
ktor.serialization.kotlinx.xml = { module = "io.ktor:ktor-serialization-kotlinx-xml", version.ref = "ktor" }
ktor.server.auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor.server.auth.jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor.server.auth.ldap = { module = "io.ktor:ktor-server-auth-ldap", version.ref = "ktor" }
ktor.server.autoHeadResponse = { module = "io.ktor:ktor-server-auto-head-response", version.ref = "ktor" }
ktor.server.bodyLimit = { module = "io.ktor:ktor-server-body-limit", version.ref = "ktor" }
ktor.server.cachingHeaders = { module = "io.ktor:ktor-server-caching-headers", version.ref = "ktor" }
ktor.server.callId = { module = "io.ktor:ktor-server-call-id", version.ref = "ktor" }
ktor.server.callLogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor.server.cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor.server.compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor.server.conditionalHeaders = { module = "io.ktor:ktor-server-conditional-headers", version.ref = "ktor" }
ktor.server.config.yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor.server.content.negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor.server.core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor.server.core.jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor.server.cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor.server.csrf = { module = "io.ktor:ktor-server-csrf", version.ref = "ktor" }
ktor.server.dataConversion = { module = "io.ktor:ktor-server-data-conversion", version.ref = "ktor" }
ktor.server.defaultHeaders = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor.server.doubleReceive = { module = "io.ktor:ktor-server-double-receive", version.ref = "ktor" }
ktor.server.forwardedHeader = { module = "io.ktor:ktor-server-forwarded-header", version.ref = "ktor" }
ktor.server.freemarker = { module = "io.ktor:ktor-server-freemarker", version.ref = "ktor" }
ktor.server.hsts = { module = "io.ktor:ktor-server-hsts", version.ref = "ktor" }
ktor.server.htmlBuilder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
ktor.server.httpRedirect = { module = "io.ktor:ktor-server-http-redirect", version.ref = "ktor" }
ktor.server.i18n = { module = "io.ktor:ktor-server-i18n", version.ref = "ktor" }
ktor.server.jetty = { module = "io.ktor:ktor-server-jetty", version.ref = "ktor" }
ktor.server.jetty.jakarta = { module = "io.ktor:ktor-server-jetty-jakarta", version.ref = "ktor" }
ktor.server.jte = { module = "io.ktor:ktor-server-jte", version.ref = "ktor" }
ktor.server.locations = { module = "io.ktor:ktor-server-locations", version.ref = "ktor" }
ktor.server.methodOverride = { module = "io.ktor:ktor-server-method-override", version.ref = "ktor" }
ktor.server.metrics = { module = "io.ktor:ktor-server-metrics", version.ref = "ktor" }
ktor.server.metrics.micrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor" }
ktor.server.mustache = { module = "io.ktor:ktor-server-mustache", version.ref = "ktor" }
ktor.server.netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor.server.openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktor" }
ktor.server.partialContent = { module = "io.ktor:ktor-server-partial-content", version.ref = "ktor" }
ktor.server.pebble = { module = "io.ktor:ktor-server-pebble", version.ref = "ktor" }
ktor.server.plugins = { module = "io.ktor:ktor-server-plugins", version.ref = "ktor" }
ktor.server.rateLimit = { module = "io.ktor:ktor-server-rate-limit", version.ref = "ktor" }
ktor.server.requestValidation = { module = "io.ktor:ktor-server-request-validation", version.ref = "ktor" }
ktor.server.resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor" }
ktor.server.servlet = { module = "io.ktor:ktor-server-servlet", version.ref = "ktor" }
ktor.server.servlet.jakarta = { module = "io.ktor:ktor-server-servlet-jakarta", version.ref = "ktor" }
ktor.server.sessions = { module = "io.ktor:ktor-server-sessions", version.ref = "ktor" }
ktor.server.sse = { module = "io.ktor:ktor-server-sse", version.ref = "ktor" }
ktor.server.statusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor.server.swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor" }
ktor.server.test.host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor.server.test.host.jvm = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
ktor.server.thymeleaf = { module = "io.ktor:ktor-server-thymeleaf", version.ref = "ktor" }
ktor.server.tomcat = { module = "io.ktor:ktor-server-tomcat", version.ref = "ktor" }
ktor.server.tomcat.jakarta = { module = "io.ktor:ktor-server-tomcat-jakarta", version.ref = "ktor" }
ktor.server.velocity = { module = "io.ktor:ktor-server-velocity", version.ref = "ktor" }
ktor.server.webjars = { module = "io.ktor:ktor-server-webjars", version.ref = "ktor" }
ktor.server.websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor.sse = { module = "io.ktor:ktor-sse", version.ref = "ktor" }
ktor.thymeleaf = { module = "io.ktor:ktor-thymeleaf", version.ref = "ktor" }
ktor.utils = { module = "io.ktor:ktor-utils", version.ref = "ktor" }
ktor.velocity = { module = "io.ktor:ktor-velocity", version.ref = "ktor" }
ktor.webjars = { module = "io.ktor:ktor-webjars", version.ref = "ktor" }
ktor.websocket.serialization = { module = "io.ktor:ktor-websocket-serialization", version.ref = "ktor" }
ktor.websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktor" }

mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
multiplatform.settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform.settings.serialization = { module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "multiplatformSettings" }
multiplatform.settings.datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "multiplatformSettings" }
multiplatform.settings.coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }

logback.classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }
slf4j.api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j.nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
voyager.navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager.screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager.bottomSheetNavigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager.tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager.transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager.koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
voyager.livedata = { module = "cafe.adriel.voyager:voyager-livedata", version.ref = "voyager" }




[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlin.plugin.serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
kotlin.jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinx.rpc = { id = "org.jetbrains.kotlinx.rpc.plugin", version.ref = "kotlinxRpc" }